# da-admin-ams — wrangler.toml.tpl
#
# Deploy flow (mirrors the helix-cloudflare-*-ams workers):
#
#   wrangler.toml.tpl (this file, committed — NO customer/env values)
#     → scripts/render-wrangler.js: substitutes $VAR placeholders from env, leaves @@VERSION@@
#   wrangler.toml (generated, gitignored)
#     → prepare-deploy.js: replaces @@VERSION@@ with the package.json version
#   wrangler-versioned.toml (generated, gitignored)
#     → wrangler deploy -c wrangler-versioned.toml
#
# Required env vars — sourced from ams-eds-terraform's environments/<env>.env
# (generated by scripts/generate-env-file.sh for content_source=da):
#   NODE_ENV                     short env name (worker name suffix + service bindings)
#   CLOUDFLARE_ACCOUNT_ID        Cloudflare account ID
#   DA_DOMAIN                    DA domain (route host + zone)
#   AEM_BUCKET_NAME              DA content R2 bucket name
#   DA_AUTH_KV_ID / DA_CONFIG_KV_ID / DA_JOBS_KV_ID   KV namespace IDs (cloudflare/00-foundation)
#   HLX_PROD_SERVER_HOST_PAGE / HLX_PROD_SERVER_HOST_LIVE
#
# Secrets (S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY, IMS_ORIGIN) are NOT templated —
# they're pushed via `wrangler secret put` by ams-eds-terraform's populate-secrets.sh.

name = "da-admin-ams-${NODE_ENV}"
main = "src/index.js"
compatibility_date = "2024-11-11"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"
keep_vars = true

routes = [
  { pattern = "admin.${DA_DOMAIN}/*", zone_name = "${DA_DOMAIN}" }
]

# Service binding to da-collab, rendered from DA_ADMIN_SERVICES (env-driven) so the
# deploy orchestrator can omit it on da-admin's FIRST pass (before da-collab exists)
# and restore it on the second pass. See scripts/deploy-da-workers.sh. Steady-state
# value (set by generate-env-file.sh): [{ binding = "dacollab", service = "da-collab-ams-<env>" }].
services = ${DA_ADMIN_SERVICES}

kv_namespaces = [
  { binding = "DA_AUTH", id = "${DA_AUTH_KV_ID}" },
  { binding = "DA_CONFIG", id = "${DA_CONFIG_KV_ID}" },
  { binding = "DA_JOBS", id = "${DA_JOBS_KV_ID}" }
]

r2_buckets = [
  { binding = "AEM_CONTENT", bucket_name = "${AEM_BUCKET_NAME}" }
]

[dev]
port = 8787

[vars]
VERSION = "@@VERSION@@"
ENVIRONMENT = "${NODE_ENV}"
DA_DOMAIN = "${DA_DOMAIN}"
DA_COLLAB = "collab.${DA_DOMAIN}"
AEM_BUCKET_NAME = "${AEM_BUCKET_NAME}"
HLX_PROD_SERVER_HOST_PAGE = "${HLX_PROD_SERVER_HOST_PAGE}"
HLX_PROD_SERVER_HOST_LIVE = "${HLX_PROD_SERVER_HOST_LIVE}"
CF_ACCOUNT_ID = "${CLOUDFLARE_ACCOUNT_ID}"
